version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  order-service:
    build:
      context: .
      dockerfile: ./services/orders/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8081:8000"

  inventory-service:
    build:
      context: .
      dockerfile: ./services/inventory/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8082:8000"

  notification-service:
    build:
      context: .
      dockerfile: ./services/notifications/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8083:8000"